version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - backend_egmxnet
    environment:
      - BACKEND_URL=http://nginx_server:8080
      - NODE_ENV=development

networks:
  backend_egmxnet:
    external: true
