version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    expose:
      - "9000"
    networks:
      - egmxnet

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - egmxnet

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: misistemaerp_sistemasegmx
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - egmxnet

networks:
  egmxnet:
    driver: bridge

volumes:
  mysql_data: